### ISSUE TITLE
Lobby server on thecity not working

### ISSUE THREAD

**Issue by rujoota** [worldofbalance/client#108]
Hi,

We were using port 9257 and thecity.sfsu.edu to login to lobby till yesterday but its not working now. We are able to login but cannot create room.
With port 9255, we are unable to login. @anuagg @worldofbalance/lobby can u please check?

**Comment by danamuise** [comment]
Change to port 9234 and do not change

**Comment by rujoota** [comment]
Not able to login with port 9234. I changed it in Assets->Scripts->Constants.cs

**Comment by anuagg** [comment]
@rujoota  did you also change your config file remote_host to thecity ? Can you check if its referring to the city or localhost.

**Comment by rujoota** [comment]
Yes its refering to thecity. @haichuand is also facing the same issue.
