### ISSUE TITLE
Species Table

### ISSUE THREAD

**Issue by brianxautumn** [worldofbalance/client#12]
SpeciesTable.GetSpecies ("Acacia");

I get Argument Null Exception every time I try this.
It also appears that SpeciesTable.Initialize() isn't even being called 
Any Ideas?

**Comment by rujoota** [comment]
Are you sure your db config are up-to-date?

**Comment by jensvdh** [comment]
I think this is the current db.conf in Development

> #This
> 
> is the configuration file for the database of this game server.
> 
> #Database URL
> #DBURL localhost
> 
> #Database name
> #DBName csc63101
> #DBName wob
> 
> #Database user name
> #DBUsername root
> 
> #Database user password
> #DBPassword newpwd
> 
> #This is the configuration file for the database of this game server.
> 
> #Database URL
> DBURL thecity.sfsu.edu
> 
> #Database name
> DBName csc63101
> 
> #Database user name
> DBUsername csc63101
> 
> #Database user password
> DBPassword csc631_01`

It should be:

> #This is the configuration file for the database of this game server.
> 
> #Database URL
> DBURL thecity.sfsu.edu
> 
> #Database name
> DBName csc63101
> 
> #Database user name
> DBUsername csc63101
> 
> #Database user password
> DBPassword csc631_01`

Correct?

**Comment by brianxautumn** [comment]
I just realized its declared in 2 places... 
Which one do I change?

<img width="514" alt="screen shot 2016-03-30 at 11 43 52 am" src="https://cloud.githubusercontent.com/assets/6754528/14153449/b7bf43aa-f66c-11e5-9567-dac4c8c036cd.png">
<img width="560" alt="screen shot 2016-03-30 at 11 43 42 am" src="https://cloud.githubusercontent.com/assets/6754528/14153450/b7d60fd6-f66c-11e5-82d7-176e02dba978.png">

**Comment by brianxautumn** [comment]
It appears that the problem is that there is not a callback for this method.
It doesn't get called. Are you guys able to access the Species Table?

<img width="496" alt="screen shot 2016-03-30 at 11 59 29 am" src="https://cloud.githubusercontent.com/assets/6754528/14153941/e8451d2c-f66e-11e5-8d0e-9df68a312513.png">

**Comment by niculistana** [comment]
@brianxautumn Please check the issue over here https://github.com/worldofbalance/wob-server/issues/9 the server's database is currently outdated, therefore cannot get the SpeciesList.
