### ISSUE TITLE
.pdb files stuck in commit and now cannot push to unity-game-client repository

### ISSUE THREAD

**Issue by dlhoff** [worldofbalance/client#14]
I had some large .pdb files in my clone of the unity-game-client repository. These came from a build. I did not include them in the .gitignore until after i had done a commit. After doing the commit i tried to push and got a size error message. So, i added them to gitignore and deleted them from my project directory and did another commit. It said that those files were deleted. However, when i do a push i still get the files too big error message. Does anyone have a suggestion about how to get the .pdb files out of the commit so that i can push to our branch of the repository? Thank you.

**Comment by rupalkhilari** [comment]
@dlhoff ,did you try doing a git remove [(git rm)](https://git-scm.com/docs/git-rm) to get rid of them from the git repo after deleting them from the directory ?

**Comment by jensvdh** [comment]
Yes. I think Git keeps a history of the files, even if they have been deleted. You need to explicitely remove them from Git by adding them to gitignore first and then running:

`git rm --cached /path/to/file.pdb`

**Comment by dlhoff** [comment]
@rupalkhilari , @jensvdh Thanks for the suggestions. I tried them. At first it said the file did not exist. So, i copied the file back into the folder, did a git add and another commit and it said that the files were added in the commit. Then i did the git rm and it said that they were removed. But when i tried to push, i get the same error message file too big. So, i tried what Jens said - git rm --cached _.pdb
and it gives the error "fatal: pathspec "_.pdb" does not match any files". The files are no longer in the project directory. They went away with the git rm. Should i use another path name? I included a screen capture. 
![g1](https://cloud.githubusercontent.com/assets/17733350/14150336/7237530e-f65d-11e5-9876-69a7a834c745.PNG)

**Comment by ilmiyoon** [comment]
git keep the history since the beginning of time. Adding something to
.gitignore does not mean that those files will be deleted in older
commits. Please try to update the commit that has the large .pdb file
(e.g., via git commit --amend) to remove it first before pushing.

**Comment by jensvdh** [comment]
Hi @dlhoff. If you want I can hop on Skype with you and walk you through the necessary steps. It's a bit hard to debug your git stuff over text.

Let me know when you are available, maybe later today?

**Comment by dlhoff** [comment]
Hit @jensvdh  That's great. I am available now until 1pm today. Are you on campus today? Can you do Google Hangout? I have not installed Skype yet.

**Comment by jensvdh** [comment]
Sure, let's try 12.15-12.30-ish ,send me a message on hangouts and we can talk there.
`jens.vanderhaeghe@gmail.com`

**Comment by dlhoff** [comment]
Confirmed. I will contact you via Google hangout at 12:15. I have office hours at 1pm, but should be done by then.

**Comment by jensvdh** [comment]
:+1:

**Comment by jensvdh** [comment]
Also @dlhoff can you install SourceTree by then? We might have to do some git magic stuff here so it'd be useful to have a visual overview.

https://www.sourcetreeapp.com/

**Comment by dlhoff** [comment]
Jens fixed the problem. I was able to push to cvg-refactor.
