### ISSUE TITLE
Can't merge changes to World.unity scene

### ISSUE THREAD

**Issue by Fito** [worldofbalance/client#18]
@worldofbalance/integration @jensvdh 
@danamuise has done a lot of wonderful UI work on the lobby, and I'm trying to merge it into development. However, since scenes are binary files, I'm unable to resolve merge conflicts.
I tried running 'git checkout --ours <filename>' but that does not seem to work. And even if it did, I don't think we want to keep only Dana's changes to the scene, since other people might have added something. Keeping development's version gets rid of his UI changes.
So I'm really stuck on this one. I found online that people use [this](http://docs.unity3d.com/Manual/SmartMerge.html) to merge Scenes. I tried it but it didn't seem to work either. (maybe I'm doing it wrong?)

Any ideas?

**Comment by Fito** [comment]
This is the branch that has Dana's changes: [lby-ui-work](https://github.com/worldofbalance/unity-game-client/tree/lby-ui-work)

**Comment by ilmiyoon** [comment]
I guess Scene as a binary file should be committed & merged in sequential order if multiple people work on it. 
Please make sure if anyone has updated scene during the time Dana has been working. If not, you can override the merge conflict with this new version of scene. If not, then Dana has to manually rebase  his changes and then push.
One of suggestion.

**Comment by jensvdh** [comment]
Are you sure the Provided unity tooling did not work?

Can you tell me the name of the scene file and the two branches we are trying to merge into each other?

Which branch is the destination branch?

I think you need to merge development back in @danamuise his branch using the tool and then you can safely merge your branch into development (once it is 0 commits behind).

Can we open a pull request for this branch? We can fix the merge conflict once the PR is open.

**Comment by Fito** [comment]
@jensvdh I'll try what you suggested, and if I can't get it to work, then I'll open a PR

**Comment by jensvdh** [comment]
Sure. You can already open a PR for that branch if you want. That doesn't mean we have to straight away merge it.

I think with the Unity Tooling we should be able to pull it off.

**Comment by danamuise** [comment]
Do you need a list of the scenes I modified? Also, it should be noted I added an asset 'Graph-Maker',  that is kind of large. I hope that is not causing the merginig problem.

**Comment by jensvdh** [comment]
It'll list you the merge conflicts when you run git status no?

**Comment by jensvdh** [comment]
Maybe we can store the Scenes as Text instead of Binary

**Comment by Fito** [comment]
@jens, @worldofbalance/lobby, @ilmiyoon 
I followed the instructions [here](http://docs.unity3d.com/Manual/SmartMerge.html) and [here](http://kihira.uk/unity-and-git-getting-them-to-play-nicely/) to set up Unity's Smart Merge tool.
I've done it a couple of times now, thinking that I might have screwed up a step. However, git is still not able to merge the scene for us. These are the files it fails to automerge:
`both modified:   Assets/Game.unity`
`both added:      Assets/Plugins/sqlite3.def.meta`
`both added:      Assets/Plugins/sqlite3.dll.meta`
`both modified:   Assets/Scenes/World.unity`
`both modified:   Assets/Scripts/World/WorldController.cs`
`both modified:   ProjectSettings/EditorBuildSettings.asset`
`both modified:   ProjectSettings/ProjectSettings.asset`

Assets/Scripts/World/WorldController.cs is easy to resolve, since it's code.
The rest are assets and scenes. Those I'm not able to resolve. 
I tried storing scenes as Text instead of Binary. When I do that, I can open the scene with a text editor.
In a text editor, Scenes look like YAML files. However, git does not show where the conflict is. It does not add the ">>>>>>>>" and "========" conflict marker to it. 

I also tried what professor Yoon suggested, and kept just Dana's Game.unity and World.unity files. Even then, all I get after logging in is a blue screen.

Any ideas?

**Comment by jensvdh** [comment]
- Use smartmerge tool for the .unity file. Then add and commit it
- Keep your copy of the sqlite3 meta files
- Manually resolve worldcontroller.cs
- Keep your version of Editor Build and Project Settings - I guess these should be treated as text and not binary.

**Comment by Fito** [comment]
I tried using the smartmerge tool to manually merge the .unity files. I ran the following command:
`/Applications/Unity/Unity.app/Contents/Tools/UnityYAMLMerge merge -p ./Assets/Scenes/World.unity ./Assets/Scenes/World.unity ./../m-World.unity ./Assets/Scenes/World.unity`
where m-World.unity is the copy from the lby-ui-work branch, and ./Assets/Scenes/World.unity is the one from development. 
I didn't get any error messages, after running it.
Then, I merged lby-ui-work into development and this time I got no merge conflicts for the .unity files. However, when I start the project, all I see is a blue screen. So I'm not sure the merge tool is actually merging the .unity files correctly.

**Comment by jensvdh** [comment]
What was the output of git status after using the merge tool?

**Comment by Fito** [comment]
After using the merge tool, git status returns:

On branch development
Your branch is ahead of 'origin/development' by 1 commit.
  (use "git push" to publish your local commits)
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
modified:   Assets/Game.unity
modified:   Assets/Scenes/World.unity
```

**Comment by Fito** [comment]
But, I don't think we want to be merging these manually anyways. The tool is merely a file merger. I had follow the steps:
- Manually make a copy of the file from one branch.
- Switch to the other branch.
- Run the merge program.
- Deleted the copied files.
- Run git merge.

This process should theoretically happen automatically by adding the following to the .giconfig file:
`[merge]`
`tool = unityyamlmerge`
`[mergetool "unityyamlmerge"]`
`trustExitCode = false`
`keepTemporaries = true`
`keepBackup = false`
`path = /Applications/Unity/Unity.app/Contents/Tools/UnityYAMLMerge/Editor/Data/Tools/UnityYAMLMerge`
`cmd = '/Applications/Unity/Unity.app/Contents/Tools/UnityYAMLMerge' merge -p "$BASE" "$REMOTE" "$LOCAL" "$MERGED"`

**Comment by jensvdh** [comment]
So you're saying the "modified" scene files are broken?

**Comment by Fito** [comment]
Yes, the merged (modified) scene files are broken. I'm now trying to figure out in what way they broke, to understand what the merge is doing.

**Comment by jensvdh** [comment]
Try to see if they output valid Yaml files

http://yaml-online-parser.appspot.com/

**Comment by Fito** [comment]
@jensvdh, @ilmiyoon, @worldofbalance/lobby 
Ok, I was able to successfully merge it.
The smartmerge tool gets us some of the way there, but there were still issues I had to go in and fix by hand. I had to remove a reference to a script that no longer existed, enable a script that was disabled in Dana's version, and I just kept Dana's ProjectSettings.asset entirely. 
Everything seems to work fine, but I would like to get many sets of eyes on it to make sure.

**Comment by jensvdh** [comment]
You can just commit your local merged version and then push that here?

**Comment by Fito** [comment]
I opened a pull request: https://github.com/worldofbalance/unity-game-client/pull/21

**Comment by jensvdh** [comment]
Can we close this issue?

**Comment by danamuise** [comment]
thanks for putting so much effort into this, I hope it wasn't something I broke!
