### ISSUE TITLE
DrawCard throwing an error

### ISSUE THREAD

**Issue by Fito** [worldofbalance/client#30]
@worldofbalance/cards-of-wild 
I'm getting the following error when I start the game:

NullReferenceException: Object reference not set to an instance of an object
Database.DrawCard (.Card card) (at Assets/Scripts/GUI/Database/Database.cs:280)
Database.MakeWindow (Int32 id) (at Assets/Scripts/GUI/Database/Database.cs:208)

**Comment by ilmiyoon** [comment]
@worldofbalance/cards-of-wild I saw a demo working yesterday. Can some answer to this issue?

**Comment by Fito** [comment]
I don't see this error anymore after merging https://github.com/worldofbalance/unity-game-client/pull/27 I'm closing this issue.
