### ISSUE TITLE
NetworkManager(script) not added to global object in the Game(scene) in development branch

### ISSUE THREAD

**Issue by laisture** [worldofbalance/client#31]
It is necessary in order to connect to the server.

![issue netwrkman](https://cloud.githubusercontent.com/assets/9082165/14366640/aa5e2854-fcc8-11e5-9fde-d70f12af6b4e.png)

**Comment by jensvdh** [comment]
Can you make a branch based off of development. Commit these changes and then make a PR?

Also it is strange that this hasn't come up yet.

@Fito did you ever see this issue?

**Comment by Fito** [comment]
@laisture The NetworkManager class is now instantiated within the Game script. It does not need to be added as a component, since it is a plain C# class now, and does not inherit from Monobehavior anymore

**Comment by Fito** [comment]
I have a pull request where that change was made but hasn't been merged yet. I'm reviewing the pull request with @anuagg today, and hopefully merging it.

**Comment by jensvdh** [comment]
OK cool. Please make merging that PR highest priority :+1: Can you reference the number here? Then I can close this issue

**Comment by Fito** [comment]
PR addressing this question has been merged: https://github.com/worldofbalance/unity-game-client/pull/24
