### ISSUE TITLE
RNO - Cannot create a room from LBY

### ISSUE THREAD

**Issue by niculistana** [worldofbalance/client#34]
I just pulled from the latest deveopment branch. It looks like the functionality to create rooms is disabled? Any pointers?

**Comment by Fito** [comment]
Are you trying to create rooms while connected to the remote server or while connected to your local server?
I am not able to create rooms while connected to the remote server, and I believe that's due to the code there being out of date. However, when I connect to my local server, I have no issues creating a room.

**Comment by laisture** [comment]
@Fito Yes you are correct, the remote server does not contain the updated WoB server code from development, because I'm also unable to create a room on the remote server.

**Comment by ilmiyoon** [comment]
@niculistana  @Fito  
When you call "remote server", are you talking about 520.x.x.x (the bracket clouds)? Or theCity?
Can you make the jar file of "local server" to thecity and test?

**Comment by Fito** [comment]
@ilmiyoon Yes, by remote server I mean the bracket clouds server.

**Comment by niculistana** [comment]
Hi all, I was able to get the jar files for the minigames (Running Rhino, Cards of Wild, Sea Divided) running on my thecity server. My problem is I am not sure what ip address to use to locate the servers I am running on my thecity server. I used the shell command `ip addr show` to see which ip address my server is on, but I do not know which from the list of ip addresses that come up after running that command. If anyone has pointers, I'd like to know how to determine which ip address is which.

On a side note, is there a working jar file somewhere for the lobby server? I'd like to test running that as well.

**Comment by jensvdh** [comment]
use the Unix command ifconfig.

Your ipaddress is the inetaddr value on the first ethernet device (usually eth0) - not the 192.168 one, that one is the local network. The localloop one is usually the 127.0.0.1 one which is used for localhost.

It's probably in the 130.212 range.

**Comment by ilmiyoon** [comment]
You can type in
"thecity.sfsu.edu:12345" if port number is 12345.
Domain server convert the domain name to ip address.

**Comment by niculistana** [comment]
I am looking to see if there is a lobby server jar file located somewhere. I only have RR, COW, and SDV. 

Edit: by @jensvdh suggestion, I built my own using `Netbeans>Build Project` feature and obtained the jar file in the `dist/` folder.

**Comment by niculistana** [comment]
I was able to create a server running on thecity.sfsu.edu, you can now connect using that. Please make sure that the following ports are being used in your client. This should be a good way to test creating and joining Running Rhino server protocols.

lobby: 9255
cow: 20038
rno: 20039
sdv: 20040

**Comment by ilmiyoon** [comment]
For those who tried this server, please let me know if worked well. 
unlike local server, "you" don't have to run the server to connect. Just use the domain name "thecity.sfsu.edu:9255" for connecting to lobby server. 
Please inform Nicu if the server is not running. Nicu will have to restart the server. (We can add feature in the future that automatically restart the server) For now, we have to manually restart whenever it crashes.

**Comment by j1george** [comment]
A couple weeks ago I was able to connect to the remote server fine. However, it suddenly stopped working at some point so I have just been working on the local server since. 
Once logged on to the local server, room creation is fine.

**Comment by niculistana** [comment]
@iamthepanda I will begin running the jar files on a dedicated machine by tonight.
