### ISSUE TITLE
Development broken?

### ISSUE THREAD

**Issue by rujoota** [worldofbalance/client#50]
I see couple of compile time errors on development branch. Its not showing exact location where its failing.

**Comment by Fito** [comment]
@rujoota could you paste the compile time errors you are seeing here?

**Comment by rujoota** [comment]
<img width="1440" alt="screen shot 2016-04-14 at 1 18 56 pm" src="https://cloud.githubusercontent.com/assets/12770146/14542491/fed25dc6-0243-11e6-9563-1c4208b2a60b.png">
<img width="1440" alt="screen shot 2016-04-14 at 1 19 33 pm" src="https://cloud.githubusercontent.com/assets/12770146/14542490/fed1dd56-0243-11e6-834d-f9fa9f1bd897.png">

**Comment by brianxautumn** [comment]
Was the last commit working?

**Comment by brianxautumn** [comment]
I just checked I don't see that. How are you getting those errors?

**Comment by rujoota** [comment]
I did nothing...just cloned development in new folder and opened game scene.

**Comment by brianxautumn** [comment]
Can you be more specific, I don't get those errors. Are you starting the main game scene?

**Comment by rujoota** [comment]
I cloned it again...and its working now....
