### ISSUE TITLE
Lobby UI Missing

### ISSUE THREAD

**Issue by Mlienk** [worldofbalance/client#51]
![lobbyuimissing](https://cloud.githubusercontent.com/assets/12202319/14542276/0032ba7c-0243-11e6-99df-6e79e4288c76.png)

New lobby UI is missing in development branch

**Comment by jensvdh** [comment]
@worldofbalance/lobby thoughts? We need our buttons back if possible ;)

**Comment by j1george** [comment]
@Mlienk @jensvdh ui is working with the current version on development thanks to @Fito
