### ISSUE TITLE
RNO - Cannot start game unless using new player

### ISSUE THREAD

**Issue by j1george** [worldofbalance/client#59]
This is a strange problem. I've been testing gameplay and it seems only new players can play Running Rhino together.
For example, say I start a game with user '1' and user '2'. I can enter the game with both players and the game runs fine. However, once I leave the game, I can no longer play the game with either of these players. I would have to make a game with 'Bob' and 'bobby'. Same issue: gameplay is fine the first time, but then these two players can't play again after leaving.
I believe it has something to do with a variable in the database, but haven't had any luck finding where it might be.

**Comment by niculistana** [comment]
@dmchung Are there any flags to whether the player is currently/finished playing in the database?

**Comment by rujoota** [comment]
@dmchung Is it possible that RR creates players only on login and not otherwise?

**Comment by j1george** [comment]
So I'm not entirely sure about this, but it does seem that it has more to do with logging on with an account than actually running the game. This is entirely speculation though based on my tests. I will have to take a better look at what is being called within the code. I've looked through the runner portions of the database, but there doesn't seem to be anything there that would cause this sort of problem.

**Comment by dmchung** [comment]
The method (the flag) that updates the DB at the end of the race is commented out. The method in question is finishRace() and it is in wob-server\src\rr\db\RaceDAO.java. I'm not sure why it was commented out, currently trying to get it to work.

**Comment by laisture** [comment]
@iamthepanda I believe there is no flag to determine if the game is finished, so the DB/Server thinks that the player is still in the game. In RaceDAO class there is a leaveRace method that tries to delete the entries into the table runner_raceinfo, but checking the database, it's not deleting the entries. @dmchung will add a flag to the database, and update it if the race finishes or if the player quits the race and tries to start a new one.

**Comment by niculistana** [comment]
@laisture @dmchung, that is a good idea, although I believe it's more of a client issue than a server/database, please see the branc: https://github.com/worldofbalance/unity-game-client/tree/dev-rno and it should work.

@iamthepanda the branch https://github.com/worldofbalance/unity-game-client/tree/dev-rno has a solution for it. I am not sure how it was fixed @jan-burianek might have some pointers. I will close his issue now.
