### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by danamuise** [worldofbalance/client#62]
I have not been able to login for the last 12 hours, "Connection Failed"

**Comment by niculistana** [comment]
@danamuise, Could you please try thecity.sfsu.edu with the following ports?

lobby: 9255
cow: 20038
rno: 20039
sdv: 20040

**Comment by danamuise** [comment]
where do I make those changes?

**Comment by j1george** [comment]
Assets > Scripts > Config.cs
and Assets > Scripts > Constants.cs

**Comment by danamuise** [comment]
thanks!
