### ISSUE TITLE
Dont Eat Me class preventing Android Build

### ISSUE THREAD

**Issue by danamuise** [worldofbalance/client#86]
When building the project for Android I get the compile error:
Assets/Scripts/DontEatMe/DemAnimalFactory.cs(3,7): error CS0246: The type or namespace name `UnityEditor' could not be found. Are you missing a using directive or an assembly reference?

When I comment out line 3: using UnityEditor; // Contains the PrefabUtility class.
in the class DemAnimalFactory.cs, the project successfully ports to Android

**Comment by rujoota** [comment]
https://github.com/worldofbalance/unity-game-client/issues/73
