### ISSUE TITLE
Latest Development Build Buttons in GUI elements on World.unity not working

### ISSUE THREAD

**Issue by echan2** [worldofbalance/client#98]
The buttons to start a game or create a multiplayer room did not work, the error I believe that was causing it was a Argument out of Range in Clock.cs on line 90, commenting out that line fixed the issue.

**Comment by rupalkhilari** [comment]
This still seems to be an issue. @worldofbalance/lobby. Not able to click on any of the buttons in the Multiplayer Game window. There are also "New Game Objects" being continuously spawned in the Game.unity scene giving errors:

```
ArgumentOutOfRangeException: Argument is out of range.
System.Globalization.DateTimeFormatInfo.GetMonthName (Int32 month) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Globalization/DateTimeFormatInfo.cs:262)
Clock.OnGUI () (at Assets/Scripts/Clock.cs:90)

```

Thanks for the workaround @echan2.

**Comment by danamuise** [comment]
we are looking into this. The mutilplayer game buttons not working looks to be a server side issue, I will see what's going on. 

The many gameObjects is coming from Zone.cs  looking into seeing why.

Nobody on the lobby team is using Clock.cs I beilieve commenting out the offending script will not cause any issues.

**Comment by rupalkhilari** [comment]
Thanks @danamuise !

**Comment by Fito** [comment]
@rupalkhilari @echan2 I pushed a fixed for the clock issue. Let me know if you still see it.

**Comment by rupalkhilari** [comment]
Thanks @Fito , it seems to be working fine now.
